ParaViewFunctions: Updated to handle Qt versions for ParaView-5.4
Patch contributed by Bruno Santos
Resolves bug-report https://bugs.openfoam.org/view.php?id=2640

diff --git a/etc/tools/ParaViewFunctions b/etc/tools/ParaViewFunctions
--- a/etc/tools/ParaViewFunctions
+++ b/etc/tools/ParaViewFunctions
@@ -174,7 +174,7 @@ addCMakeVariable()
 {
     for var in $*
     do
-	CMAKE_VARIABLES="$CMAKE_VARIABLES -D$var"
+        CMAKE_VARIABLES="$CMAKE_VARIABLES -D$var"
     done
 }
 
@@ -374,14 +374,26 @@ addQtSupport()
         QtMajor=$1
         QtMinor=$2
 
-        if [ $QtMajor -lt 4 -o $QtMajor -eq 4 -a $QtMinor -lt 5 ]
+        if [ $QtMajor -lt 4 -o $QtMajor -eq 4 -a $QtMinor -lt 7 ]
         then
-            echo "*** Error: Qt version provided < 4.5"
-            echo "***     Please use the -qmake option to specify the location of a version of Qt >= 4.5"
+            echo "*** Error: Qt 4 version provided < 4.7"
+            echo "***     Please use the -qmake option to specify the location of a version of Qt >= 4.7"
             echo "***     e.g."
-            echo "***         -qmake /usr/local/qt-4.6.2/bin/qmake"
-            echo "***         -qmake $installBASE/qt-4.6.2/bin/qmake"
+            echo "***         -qmake /usr/local/qt-4.7.2/bin/qmake"
+            echo "***         -qmake $installBASE/qt-4.7.2/bin/qmake"
             exit 1
+        elif [ $QtMajor -eq 5 -a $QtMinor -lt 6 ]
+        then
+            echo "*** Error: Qt 5 version provided < 5.6"
+            echo "***     Please use the -qmake option to specify the location of a version of Qt >= 5.6"
+            echo "***     e.g."
+            echo "***         -qmake /usr/local/qt-5.6.0/bin/qmake"
+            echo "***         -qmake $installBASE/qt-5.6.0/bin/qmake"
+            exit 1
+        else
+            # Enforce the Qt version to be used, so that users don't have to
+            # guess how to tell ParaView to use the desired Qt version
+            addCMakeVariable "PARAVIEW_QT_VERSION=$QtMajor"
         fi
     else
         echo "*** Error: cannot find qmake either at \$QMAKE_PATH or in current \$PATH"
